In [2]:
import pandas as pd
stats = pd.read_csv('game_stats.csv')

In [3]:
stats.head()

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
0,14-06-2018,Russia,Saudi Arabia,5,40,13,7,3,3,6,...,0,0,0,Yes,12.0,Group Stage,No,0,NaN,NaN
1,14-06-2018,Saudi Arabia,Russia,0,60,6,0,3,3,2,...,0,0,0,No,NaN,Group Stage,No,0,NaN,NaN
2,15-06-2018,Egypt,Uruguay,0,43,8,3,3,2,0,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
3,15-06-2018,Uruguay,Egypt,1,57,14,4,6,4,5,...,0,0,0,Yes,89.0,Group Stage,No,0,NaN,NaN
4,15-06-2018,Morocco,Iran,0,64,13,3,6,4,5,...,1,0,0,No,NaN,Group Stage,No,0,1.0,90.0

In [4]:
stats.shape

(128, 27)

In [5]:
stats.describe()

,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,Offsides,Free Kicks,Saves,...,Passes,Distance Covered (Kms),Fouls Committed,Yellow Card,Yellow & Red,Red,1st Goal,Goals in PSO,Own goals,Own goal Time
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,...,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,94.000000,128.000000,12.0,12.000000
mean,1.320312,49.992188,12.593750,3.914062,5.273438,3.359375,4.718750,1.343750,14.890625,2.726562,...,462.648438,106.664062,13.546875,1.695312,0.015625,0.015625,39.457447,0.203125,1.0,45.833333
std,1.156519,10.444074,5.245827,2.234403,2.409675,2.403195,2.446072,1.193404,4.724262,2.049447,...,151.186311,11.749537,4.619131,1.325454,0.124507,0.124507,24.496506,0.807049,0.0,29.978275
min,0.000000,25.000000,3.000000,0.000000,1.000000,0.000000,0.000000,0.000000,5.000000,0.000000,...,189.000000,80.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.0,12.000000
25%,0.000000,42.000000,9.000000,2.000000,4.000000,1.750000,3.000000,0.000000,11.000000,1.000000,...,351.000000,101.000000,10.000000,1.000000,0.000000,0.000000,18.250000,0.000000,1.0,21.750000
50%,1.000000,50.000000,12.000000,3.500000,5.000000,3.000000,5.000000,1.000000,15.000000,2.000000,...,462.000000,104.500000,13.000000,2.000000,0.000000,0.000000,39.000000,0.000000,1.0,35.000000
75%,2.000000,58.000000,15.000000,5.000000,7.000000,4.000000,6.000000,2.000000,18.000000,4.000000,...,555.250000,109.000000,16.000000,2.000000,0.000000,0.000000,54.750000,0.000000,1.0,75.750000
max,6.000000,75.000000,26.000000,12.000000,11.000000,10.000000,11.000000,5.000000,26.000000,9.000000,...,1137.000000,148.000000,25.000000,6.000000,1.000000,1.000000,90.000000,4.000000,1.0,90.000000

In [6]:
stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    128 non-null    object
 1   Team                    128 non-null    object
 2   Opponent                128 non-null    object
 3   Goal Scored             128 non-null    int64
 4   Ball Possession %       128 non-null    int64
 5   Attempts                128 non-null    int64
 6   On-Target               128 non-null    int64
 7   Off-Target              128 non-null    int64
 8   Blocked                 128 non-null    int64
 9   Corners                 128 non-null    int64
 10  Offsides                128 non-null    int64
 11  Free Kicks              128 non-null    int64
 12  Saves                   128 non-null    int64
 13  Pass Accuracy %         128 non-null    int64
 14  Passes                  128 non-null    int64
 15  Distance Covered (Kms)  128 non-null    int64
 16  Fouls Committed         128 non-null    int64
 17  Yellow Card             128 non-null    int64
 18  Yellow & Red            128 non-null    int64
 19  Red                     128 non-null    int64
 20  Man of the Match        128 non-null    object
 21  1st Goal                94 non-null     float64
 22  Round                   128 non-null    object
 23  PSO                     128 non-null    object
 24  Goals in PSO            128 non-null    int64
 25  Own goals               12 non-null     float64
 26  Own goal Time           12 non-null     float64
dtypes: float64(3), int64(18), object(6)
memory usage: 27.1+ KB

In [ ]:
#from above summary we can see that the number of missing values 
#in column 'Own goals' and 'Own goal Time' entail a 
#high percentage of the total sample
#But column '1st Goal' has less missing values, therefore it will
#be filled with appropriate values i.e interpolation

In [ ]:
import numpy as np
pd.Series(np.where(stats.PSO.values == 'Yes', 1, 0),
          sample.index)

pd.Series(np.where(stats.'Man of the Match'.values == 'Yes', 1, 0),
          sample.index)

In [ ]:
stats_clean

In [7]:
col_list = list(stats_clean.select_dtypes(include=['object']).columns)
stats_clean = stats.drop(col_list,axis=1)
stats_clean.info()

['Date', 'Team', 'Opponent', 'Man of the Match', 'Round', 'PSO']

In [ ]:
import seaborn as sns
sns.set_style("whitegrid")

import matplotlib.pylab as plt
%matplotlib inline 
plt.style.use('seaborn-whitegrid')
plt.rc('text', usetex = True)
plt.rc('font', family = 'times')
plt.rc('xtick', labelsize = 10) 
plt.rc('ytick', labelsize = 10) 
plt.rc('font', size = 12) 
plt.rc('figure', figsize = (12, 5))

In [ ]:
indexes = [0, 2, 4, 5, 6, 12] #To plot just some of the variables
df = pd.DataFrame(stats_clean.data[:,indexes], columns = stats_clean.feature_names[indexes])
#df['price'] = stats_clean.target
corrmat = df.corr()
# Draw the heatmap using seaborn
sns.heatmap(corrmat, vmax = .11, square = True)